BUNDLES = [
    "//apps/satellite/app:onos-apps-satellite-app",
]

onos_app(
    category = "Graphical User Interface",
    description = "ONOS OSGi GUI2 Custom-View app satellite.",
    included_bundles = BUNDLES,
    title = "Optical Application",
    url = "http://onosproject.org",
)
